
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd g1t6-ljps
        python -m pip install --upgrade pip
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run integration tests
      run: |
        cd g1t6-ljps/Backend
        python Integration_Test_LJ.py
        python Integration_Test_Courses.py
        python Integration_Test_Role.py
        python Integration_Test_Staff.py
        python Integration_Test_Skill.py
